name: gdb9
url: "https://drive.google.com/uc?id=1ys1rvwixeZBiCPg8Kj8D65iFl8zJDdTu"
file_format:
  structure: sdf
  properties: csv
available_targets:
  - homo
  - lumo
  - gap
default_targets:
  - homo
  - lumo
  - gap
recommended_parameters:
  batch_size: 64
  epochs: 1
  model_size: "84m"
  split: "random"
